name: cDisposal
version: 2.1
author: Bingoo
main: cDisposal.Main
description: A plugin that makes it possible to have a trash can.
api-version: 1.13

commands:
  soptunna:
    aliases: [af, avfall, st]
  cdisposalrelod: